### ISSUE TITLE
Question: Reply File Error

### ISSUE THREAD

**Issue by SuperlativeEntity** [jeffmess/Bankserv#15]
Hi, hope you're well?

This is a long shot, but do you have any idea what this reply file error message means?

USER BRANCH NOT = CONTROL

Regards

**Comment by teaspoon** [comment]
I have seen that error before. If I'm not mistaken the account is not registered at your bank to process BankServ transactions. They will need to add it on their end.

**Comment by SuperlativeEntity** [comment]
Thanks for your reply! The account was created but Absa didn't link a branch code to the account. The test file works 100% now, wohoo.

**Comment by jeffmess** [comment]
Just curiously, are you using this library? We are no longer maintaining since we have rewritten it from the ground up in a private more stable library which no longer needs any hand holding.

**Comment by SuperlativeEntity** [comment]
Hi Jeff, I am not using it. I just did a Google search for an error message and it happened to appear in your repo.
